praktikum/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story4/', include(('story_4.urls', 'story4'), namespace="story_4")),
]

story_4/urls.py
from django.conf.urls import re_path
from .views import index, activities, add_message, delete_todo

#url for app
urlpatterns = [
	re_path(r'^$', index, name='index'),
	re_path(r'^activities/$',  activities, name='activities'),
	re_path(r'^add_message/$', add_message, name='add_message'),
	re_path(r'^(?P<id>[0-9]+)/delete/$', delete_todo, name='delete_todo')
]

story_4/models.py
from django.db import models

# Create your models here.
class ToDo(models.Model):
	date = models.DateField()
	time = models.TimeField()
	categories = models.TextField(null=True)
	activities = models.TextField()
	place = models.TextField(null=True)

story_4/forms.py
from django import forms

class Add_ToDo(forms.Form):

	attrs = {
        'class': 'form-control',
    }

	date = forms.DateField(label='date', required=False, widget=forms.DateInput(attrs=attrs))
	time = forms.TimeField(label = 'time', required=False, widget=forms.DateTimeInput(attrs=attrs))
	categories = forms.CharField(label ='categories', required=False, widget=forms.TextInput(attrs=attrs))
	activities = forms.CharField(label = 'activities', required=False, widget=forms.TextInput(attrs=attrs))
	place = forms.CharField(label = 'place', required=False, widget=forms.TextInput(attrs=attrs))

story_4/views.py
from django.shortcuts import render
from .forms import Add_ToDo
from .models import ToDo
from datetime import datetime
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404

# Enter your name here
nama = "Hanna Jannatunna'iim"
aboutMe = '''Hi! I’m Hanna. I’m a person who likes to work hard and learn new things.
		I also easily adapt to the new environment. Creating and organizing events is fun for me.
		I do what i love and love what i do.'''
response = {'name': nama, 'about' : aboutMe}


# Create your views here.
def index(request):
	return render(request, 'profile_web.html', response)

def activities(request):
	toDoList = ToDo.objects.all().values()
	response['toDoList'] = convert_queryset_into_json(toDoList)
	response['form'] = Add_ToDo
	return render(request, 'project.html', response)

# method untuk membuat entry baru
def add_message(request):
	form = Add_ToDo(request.POST)
	if request.method == 'POST' and form.is_valid():
		print(request.POST)
		date_converted = datetime.strptime(request.POST['date'], '%Y-%m-%d')
		time_converted = datetime.strptime(request.POST['time'], '%H:%M')
		message = ToDo(date=date_converted, time=time_converted,categories=request.POST['categories'], activities=request.POST['activities'], place=request.POST['place'])
		message.save()
		
	return HttpResponseRedirect('/story4/activities/')

def convert_queryset_into_json(queryset):
    ret_val = []
    for data in queryset:
        ret_val.append(data)
    return ret_val

def delete_todo(request, id=None):
	todoObject = get_object_or_404(ToDo, pk=id)
	todoObject.delete()
	return HttpResponseRedirect('/story4/activities/')

story_4/templates/header/header.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.2/css/all.css" integrity="sha384-rtJEYb85SiYWgfpCr0jn174XgJTn4rptSOQsMroFBPQSGLdOC5IbubP6lJ35qoM9" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Monsieur+La+Doulaise|Noto+Sans|Salsa|Roboto+Condensed&display=swap" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
	<div class="fixed-top">
		<div class="container-fluid" id="menuBar">
			<div class="row">
			    <div class="col">
			      <h2 id="sign">Hanna</h2>
			    </div>
			    <div class="col">
			      <nav class="navbar navbar-expand-lg navbar-light float-md-right">
		  			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    				<span class="navbar-toggler-icon"></span>
		    		</button>
			    		<div class="collapse navbar-collapse" id="navbarNav">
						    <ul class="navbar-nav">
						      <li class="nav-item">
						        <a class="nav-link" href="{% url 'story_4:index' %}#homePage">Home</a>
						      </li>
						      <li class="nav-item">
						        <a class="nav-link" href="{% url 'story_4:index' %}#profilePage">Profile</a>
						      </li>
						      <li class="nav-item">
						        <a class="nav-link" href="{% url 'story_4:index' %}#abilitiesPage">Abilities</a>
						      </li>
						      <li class="nav-item">
						        <a class="nav-link" href="{% url 'story_4:index' %}#experiencePage">Experience</a>
						      </li>
						      <li class="nav-item">
						        <a class="nav-link" href="{% url 'story_4:index' %}#contactPage">Contact</a>
						      </li>
						      <li class="nav-item">
						        <a class="nav-link" href="{% url 'story_4:activities' %}">Activities</a>
						      </li>
						    </ul>
						</div>
					</nav>	
			    </div>
			</div>
		</div>
	</div>
<

story_4/templates/profile_web.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Profile Hanna Jannatunna'iim</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.2/css/all.css" integrity="sha384-rtJEYb85SiYWgfpCr0jn174XgJTn4rptSOQsMroFBPQSGLdOC5IbubP6lJ35qoM9" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Monsieur+La+Doulaise|Noto+Sans|Salsa|Roboto+Condensed&display=swap" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
	<header>
		{% include "header/header.html" %}
	</header>
	<a name="home"><div id="homePage">
		<div class="row">
		    <div id='textHome' class="col">
		    	<div id="Hello" class="row">
		    		<h1>Hello!</h1>
					<h3>Want to find out more?<br>let's explore all about me!</h3>
		    	</div>
		    	<div id="arrow" class="row">
		    		<a href="#profilePage"><i class="fas fa-chevron-down fa-5x"></i></a>
		    	</div>
		    </div>
		    <div id="fotoHome" class="col">
		      <img id="fotoHomePage" src="{% static 'css/fotoProfile.png' %}">
		    </div>
		</div>
	</div></a>
	<a name="profil"><div id="profilePage">
		<div class="inheritMenuBar"></div>
		<div id="isiProfilePage" class="row">
		    <div class="col">
		    	<h2 class="Title">Welcome to<br>My Profile!</h2>
		    </div>
		    <div class="col">
		    	<p id="aboutMe" >{{about}}</p>
		    </div>
		    <div class="w-100"></div>
		    <div class="col">
		    	<div id="profile">
		    		 <p>Name : {{name}}</p>
		    		 <p>Education:<ul type="disc">
									<li>Information System, University of Indonesia (2018 - present)</li>
									<li>SMAN 38 Jakarta (2015 - 2018)</li>
									<li>MTsN 41 Al-Azhar Asy-Syarif (2012 - 2015)</li>
									<li>Min Al-Azhar Asy-Syarif (2006 - 2012)</li>
									</ul>
		    		 </p>
		    	</div>
			</div>
			<div id="foto" class="col">
				<img id="image2" src="{% static 'css/fotoProfile2.png' %}">
			</div>
		</div>
	</div></a>
	<a name="abilities"><div id="abilitiesPage">
		<div class="inheritMenuBar"></div>
		<div class="pageTitle">
			<h2 class="TitleLeft">My Abilities</h2>
		</div>
		<div>
			<div class="row">
				<div class="col">
					<div id="hardSkill">
						<ul class="listAbilities">
							<li>Ms.Word, Ms.Excel,Ms.Power Point<img src="{% static 'css/progress90.png' %}" class="progress microsoft"></li>
							<li>Python<img src="{% static 'css/progress75.png' %}" class="progress"></li>
							<li>Java<img src="{% static 'css/progress80.png' %}" class="progress"></li>
							<li>HTML<img src="{% static 'css/progress75.png' %}" class="progress"></li>
							<li>CSS<img src="{% static 'css/progress70.png' %}" class="progress"></li>
						</ul>
					</div>
				</div>
				<div class="col">
					<div class="row">
				   		<div class="col"><i class="fas fa-long-arrow-alt-left fa-10x"></i></div>
				    	<div id="titleAbilities1" class="col"><p>Hard Skill</p></div>
					</div>
				</div>
			</div>
		</div>
		<div>
			<div class="row">
				<div class="col">
					<div class="row">
						<div id="titleAbilities2" class="col"><p>Soft Skill</p></div>
				   		<div id="rightArrow" class="col"><i class="fas fa-long-arrow-alt-right fa-10x"></i></div>
				   	</div>
				</div>
				<div class="col">
					<div id="softSkill">
						<ul class="listAbilities">
							<li>Communication<img src="{% static 'css/progress90.png' %}" class="progress"></li>
							<li>Management<img src="{% static 'css/progress85.png' %}" class="progress"></li>
							<li>Leadership<img src="{% static 'css/progress80.png' %}" class="progress"></li>
							<li>Innovative and Creative<img src="{% static 'css/progress85.png' %}" class="progress"></li>
							<li>Team Work<img src="{% static 'css/progress90.png' %}" class="progress"></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div></a>
	<a name="experience"><div id="experiencePage">
		<div class="inheritMenuBar"></div>
		<div class="pageTitle">
			<h2 class="TitleLeft">My Experience</h2>
		</div>
		<div>
			<div class="row">
				<div class="col">
					<p class="titleExperience">Organizations</p>
					<ul class="listOrganizations">
							<li class="organization"><p class="period">February 2019 - January 2020</p>
								<p>Staff of Human Resource Development Beruau at BEM Faculty of Computer Science 2019<br>
								 (HRD of the Information Technology Development Bureau and creating the internal events )</p>
							</li>
							<li class="organization"><p class="period">October 2016 - October 2017</p>
								<p>President at MPK SMAN 38 Jakarta<br>
								( Responsible for all members )</p>
							</li>
							<li class="organization"><p class="period">September 2015 - October 2016</p>
								<p>Flag Ceremony Overseer Subsie at MPK SMAN 38 Jakarta<br>
								( Oversee flag ceremony every Monday and national ceremony )</p>
							</li>
					</ul>
				</div>
				<div class="col">
					<p class="titleExperience">Committee</p>
					<ul class="listCommittee">
							<li class="organization"><p class="period">April 2019 - November 2019</p>
								<p>Staff of Event Division PMB Faculty of Computer Science 2019</p>
								<p>( Person in charge introduction of the faculty academic system event )</p>
							</li>
							<li class="organization"><p class="period">February 2019 - September 2019</p>
								<p>Staff of Event Division COMPFEST 11</p>
								<p>( Organize related to the stage )</p>
							</li>
							<li class="organization"><p class="period">December 2018 - January 2019</p>
								<p>Staff of Event Division Odd Graduation Faculty of Computer Science</p>
								<p>( Creating the MC script )</p>
							</li>
					</ul>
				</div>
			</div>
		</div>
	</div></a>
	<a name="contact"><div id="contactPage">
		<div class="inheritMenuBar"></div>
		<div class="pageTitle">
			<h2 class="TitleLeft">Connect with Me!</h2>
		</div>
		<div class="row">
			<div class="col">
				<div class="row">
					<div id="ig" class="col" ><a href="https://www.instagram.com/hanna_jtm/" style="color:black"><p id="icon"><i class="fab fa-instagram fa-5x"></i></p></a></div>
					<div  id="userIG" class="col"><a href="https://www.instagram.com/hanna_jtm/" style="color:black"><p id="idUser">@hanna_jtm</p></a></div>
				</div>
			</div>
			<div class="col">
				<div class="row">
					<div id="userEmail" class="col"><a  href="https://https://mail.google.com" style="color:black"><p id="idUser">hanna14jtm@gmail.com</p></a></div>
					<div id="email" class="col"><a href="https://https://mail.google.com" style="color:black"><p id="icon"><i class="fas fa-envelope fa-5x"></i></p></a></div>
				</div>
			</div>
			<div class="w-100"></div>
			<div class="col">
				<div class="row">
					<div id="twitter" class="col"><a href="https://twitter.com/hannaJtm" style="color:black"><p id="icon"><i class="fab fa-twitter fa-5x"></i></p></a></div>
					<div id="userTwitter" class="col"><a href="https://twitter.com/hannaJtm" style="color:black"><p id="idUser">@hannaJtm</p></a></div>
				</div>
			</div>
			<div class="col">
				<div class="row">
					<div id="userLinkedin" class="col"><a href="https://www.linkedin.com/in/hanna-jtm/" style="color:black"><p id="idUser">linkedin.com/in/hanna-jtm/</p></a></div>
					<div id="linkedin" class="col"><a href="https://www.linkedin.com/in/hanna-jtm/" style="color:black"><p id="icon"><i class="fab fa-linkedin-in fa-5x"></i></p></a></div>
				</div>
			</div>
			<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
	</div></a>
</body>
</html>

story_4/templates/project.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Activities Page</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.2/css/all.css" integrity="sha384-rtJEYb85SiYWgfpCr0jn174XgJTn4rptSOQsMroFBPQSGLdOC5IbubP6lJ35qoM9" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Monsieur+La+Doulaise|Noto+Sans|Salsa|Roboto+Condensed&display=swap" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
		<header>
			{% include "header/header.html" %}
		</header>
		<div id="activitiesPage">
			<div class="inheritMenuBar"></div>
			<div class="pageTitle">
				<h2 class="TitleLeft">My Activities</h2>
			</div>
			<div class="row">
				<div class="col">
					<table class="table table-borderless">
				        <thead>
				          <tr>
				            <th scope="col">Date</th>
				            <th scope="col">Time</th>
				            <th scope="col">Categories</th>
				            <th scope="col">Activities</th>
				            <th scope="col">Place</th>
				            <th scope="col"></th>
				          </tr>
				        </thead>
				        <tbody>
				          <tr>
				          {% for data in toDoList %}
				         	  <td class="date"> {{ data.date }} </td>
				              <td class="time"> {{ data.time }} </td>
				              <td class="categories"> {{ data.categories }} </td>
				              <td class="todo"> {{ data.activities }} </td>
				              <td class="place"> {{ data.place }} </td>
				              <td><form action="{% url 'story4:delete_todo' data.id %}" method="GET">
  									<button type="submit" class="btn btn-primary">Delete</button>
								  </form>
							 </td>
				          </tr>
				          {% endfor %}
				        </tbody>
				     </table>
				</div>
				<div class="col">
					<form id="form" method="POST" action="{% url 'story4:add_message' %}">
						{% csrf_token %}
					  	{{ form }}
					  	<br>
					  <button type="submit" class="btn btn-primary">Submit</button>
					</form>
				</div>
			</div>
		</div>
</body>
</html>